services:
  pgdatabase:
    container_name: pgdatabase
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - "./ny_taxi_data:/var/lib/postgresql/data.rw"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "/ny_taxi_data_pgadmin:/var/lib/pgadmin.rw"

volumes:
  ny_taxi_data:
    name: ny_taxi_data
  ny_taxi_data_pgadmin:
    name: ny_taxi_data_pgadmin